In [9]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members!

In [8]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT name, SUM(
CASE WHEN memid =0
THEN slots * guestcost
ELSE slots * membercost
END ) AS 'Revenue'
FROM Bookings AS B
INNER JOIN Facilities AS F ON B.facid = F.facid
GROUP BY name
HAVING Revenue <1000
ORDER BY Revenue
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order

In [21]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT a.`surname`, a.`firstname`, b.`firstname` || ' ' || b.`surname`
FROM Members AS a
LEFT JOIN Members AS b ON b.`memid` = a.`recommendedby`
WHERE a.`memid` <> 0
ORDER BY a.surname, a.firstname
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader', 'Florence', 'Ponder Stibbons')
('Baker', 'Anne', 'Ponder Stibbons')
('Baker', 'Timothy', 'Jemima Farrell')
('Boothe', 'Tim', 'Tim Rownam')
('Butters', 'Gerald', 'Darren Smith')
('Coplin', 'Joan', 'Timothy Baker')
('Crumpet', 'Erica', 'Tracy Smith')
('Dare', 'Nancy', 'Janice Joplette')
('Farrell', 'David', None)
('Farrell', 'Jemima', None)
('Genting', 'Matthew', 'Gerald Butters')
('Hunt', 'John', 'Millicent Purview')
('Jones', 'David', 'Janice Joplette')
('Jones', 'Douglas', 'David Jones')
('Joplette', 'Janice', 'Darren Smith')
('Mackenzie', 'Anna', 'Darren Smith')
('Owen', 'Charles', 'Darren Smith')
('Pinker', 'David', 'Jemima Farrell')
('Purview', 'Millicent', 'Tracy Smith')
('Rownam', 'Tim', None)
('Rumney', 'Henrietta', 'Matthew Genting')
('Sarwin', 'Ramnaresh', 'Florence Bader')
('Smith', 'Darren', None)
('Smith', 'Darren', None)
('Smith', 'Jack', 'Darren Smith')
('Smith', 'Tracy', None)
('Stibbons', 'Ponder', 'Burton Tracy')
('Tracy', 'Burton', None)
('Tupperware', 'Hyacinth', None)
('Worthington-Smyth', 'Henry', 'Tracy Smith')

Q12: Find the facilities with their usage by member, but not guests

In [33]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT M.`firstname` || ' ' || M.`surname`, F.name, COUNT(B.bookid)
        FROM Bookings AS B
        INNER JOIN Facilities AS F ON B.facid = F.facid
        INNER JOIN Members as M ON B.memid = M.memid
        WHERE B.memid <> 0
        GROUP BY B.memid
        ORDER BY F.name
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Nancy Dare', 'Badminton Court', 117)
('Florence Bader', 'Badminton Court', 120)
('Anna Mackenzie', 'Badminton Court', 126)
('Douglas Jones', 'Badminton Court', 14)
('Henry Worthington-Smyth', 'Badminton Court', 41)
('Millicent Purview', 'Badminton Court', 16)
('Erica Crumpet', 'Badminton Court', 7)
('Tim Rownam', 'Massage Room 1', 408)
('Janice Joplette', 'Massage Room 1', 159)
('Jack Smith', 'Massage Room 1', 89)
('Matthew Genting', 'Massage Room 2', 72)
('David Pinker', 'Snooker Table', 71)
('Joan Coplin', 'Snooker Table', 53)
('Henrietta Rumney', 'Snooker Table', 20)
('Hyacinth Tupperware', 'Snooker Table', 16)
('Darren Smith', 'Table Tennis', 261)
('Jemima Farrell', 'Table Tennis', 80)
('Tracy Smith', 'Tennis Court 1', 210)
('Gerald Butters', 'Tennis Court 1', 163)
('Charles Owen', 'Tennis Court 1', 131)
('Anne Baker', 'Tennis Court 1', 118)
('David Farrell', 'Tennis Court 1', 34)
('John Hunt', 'Tennis Court 1', 15)
('Burton Tracy', 'Tennis Court 2', 176)
('Tim Boothe', 'Tennis Court 2', 188)
('Ponder Stibbons', 'Tennis Court 2', 104)
('David Jones', 'Tennis Court 2', 115)
('Timothy Baker', 'Tennis Court 2', 166)
('Ramnaresh Sarwin', 'Tennis Court 2', 70)

Q13: Find the facilities usage by month, but not guests

In [36]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT strftime('%m', B.starttime) AS Month, F.name, COUNT(B.bookid)
        FROM Bookings AS B
        INNER JOIN Facilities AS F ON B.facid = F.facid
        GROUP BY Month, F.name
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 'Badminton Court', 56)
('07', 'Massage Room 1', 123)
('07', 'Massage Room 2', 12)
('07', 'Pool Table', 110)
('07', 'Snooker Table', 75)
('07', 'Squash Court', 75)
('07', 'Table Tennis', 51)
('07', 'Tennis Court 1', 88)
('07', 'Tennis Court 2', 68)
('08', 'Badminton Court', 146)
('08', 'Massage Room 1', 224)
('08', 'Massage Room 2', 40)
('08', 'Pool Table', 291)
('08', 'Snooker Table', 159)
('08', 'Squash Court', 170)
('08', 'Table Tennis', 147)
('08', 'Tennis Court 1', 146)
('08', 'Tennis Court 2', 149)
('09', 'Badminton Court', 181)
('09', 'Massage Room 1', 282)
('09', 'Massage Room 2', 59)
('09', 'Pool Table', 435)
('09', 'Snooker Table', 210)
('09', 'Squash Court', 195)
('09', 'Table Tennis', 205)
('09', 'Tennis Court 1', 174)
('09', 'Tennis Court 2', 172)